Host average rating
tinylunark/lunark-front pull request #59
Opened 2024-01-07 18:37 UTC by vradovic

This PR changes the host average rating to be fetched from backend.

2024-01-08 09:54 UTC, MomirMilutinovic approved these changes
Looks good. 
There is still a way to refresh the average rating of a host when a review is deleted.

2024-01-08 09:54 UTC, MomirMilutinovic commented on src/app/host/host-page/host-page.component.html
> +        <app-reviews [id]="id || 0" [reportingAllowed]="reportingAllowed" *ngIf="reviews != null"></app-reviews>
I suggest leaving this line as is.
```suggestion
        <app-reviews [id]="id || 0" [reportingAllowed]="reportingAllowed" *ngIf="reviews != null" (reviewDeleted)="calculateAverageRating()"></app-reviews>
```

2024-01-08 09:54 UTC, MomirMilutinovic commented on src/app/host/host-page/host-page.component.ts
> -    this.averageRating = this.reviews.map(review => review.rating).reduce((a, b) => a + b) / this.reviews.length;
I recommend changing these lines so they fetch the average rating again and not deleting this method.

2024-01-08 10:08 UTC, MomirMilutinovic commented
I have rebased this branch on top of the current develop branch. Currently, the host page 404s because the backend for checking eligibility to report a host has not yet been merged (https://github.com/tinylunark/lunark-back/pull/73). 
I recommend delaying the merging of this PR until the aforementioned backend PR has been merged.

2024-01-08 16:12 UTC, MomirMilutinovic commented on src/app/http-interceptors/page-not-found.interceptor.ts
> +      // })
What issues is `PageNotFoundInterceptor` causing?
If it being invoked when acessing `api/reports/accounts/host-report-eligibilty` is the problem, then I don't recommend commenting this code out as merging that backend PR I mentioned would solve the problem.

2024-01-08 16:12 UTC, MomirMilutinovic commented on src/app/http-interceptors/page-not-found.interceptor.ts
> +      // })
```suggestion
      catchError((error: HttpErrorResponse) => {
        if (error.status === 404) {
          this.router.navigate(['/404']);
        }
        return throwError(() => error)
      })
```

2024-01-08 16:15 UTC, MomirMilutinovic requested changes
I don't know if it's a good idea to comment out `PageNotFoundInterceptor`.
Also, I think it's cleaner to just remove it from the list of interceptors than to comment it out, since that makes it clearer that it is disabled.

2024-01-09 12:26 UTC, vradovic commented on src/app/http-interceptors/page-not-found.interceptor.ts
> +      // })
Resolved with merged backend PR.

2024-01-09 18:50 UTC, MomirMilutinovic approved these changes
Looks good.

2024-01-09 18:50 UTC, merged